### ISSUE TITLE
Need contrained least-squares fitting

### ISSUE THREAD

**Issue by jsklimavicz** [jsklimavicz/Plate_Analyzer#13]
Requires new C functions without derivs

**Comment by jsklimavicz** [comment]
Needs more debugging in array mode. 

```
Traceback (most recent call last):
  File "/home/jklimavicz/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/jklimavicz/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/jklimavicz/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/jklimavicz/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/jklimavicz/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/jklimavicz/Documents/Plate_Analyzer/stats/curvell.py", line 162, in array_curve
    return ff.switch_array_fitter(switch, self.conc, beta_probs, init_prob)
  File "/home/jklimavicz/Documents/Plate_Analyzer/stats/functionfit.py", line 1073, in switch_array_fitter
    biter, blen = b_out.shape
UnboundLocalError: local variable 'b_out' referenced before assignment
```

**Comment by jsklimavicz** [comment]
Local variable issue solved for python version, but C-based version causes segmentation fault....
